### Test Config Device API

# Lấy config hiện tại của thiết bị
GET http://localhost:3000/devices/{{deviceId}}/config

###

# Cập nhật config cho thiết bị
POST http://localhost:3000/devices/{{deviceId}}/config
Content-Type: application/json

{
  "ssid": "NewWiFiSSID",
  "password": "NewPassword123",
  "serverIP": "192.168.1.100"
}

###

# Test với device ID cụ thể (thay thế bằng ID thực tế)
GET http://localhost:3000/devices/64f8a1b2c3d4e5f6a7b8c9d0/config

###

POST http://localhost:3000/devices/64f8a1b2c3d4e5f6a7b8c9d0/config
Content-Type: application/json

{
  "ssid": "MyWiFiNetwork",
  "password": "MyPassword123",
  "serverIP": "192.168.100.82"
} 